name: tag a new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version'
        required: true
        type: string

      newversion:
        description: 'Next desired version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          echo this is the new tag version ${{github.event.inputs.version}}


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build
        run: |
          mvn clean install

      - name: set the Tag version
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"

          mvn versions:set -DnewVersion=${{github.event.inputs.version}}

      - name: Create tag
        uses: ncipollo/release-action@v1
        with:
          bodyFile: changelog/${{github.event.inputs.version}}.md
          tag: ${{github.event.inputs.version}}


      - name: Upgrade Version
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"

          mvn versions:set -DnewVersion=${{github.event.inputs.newversion}}
          git commit -am "new version release ${{github.event.inputs.newversion}}"
          git push
#
#      - name: Publish to GitHub Packages
#        run: mvn --batch-mode deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}