name: tag a new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version'
        required: true
        type: string

      newversion:
        description: 'Next desired version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Build
        run: |
          mvn clean install -q

      - name: set the Tag version
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config user.signingkey ${{ secrets.GPG_KEYNAME }}

          mvn versions:set -DnewVersion=${{github.event.inputs.version}}
          git commit -am "[skip ci] new version release ${{github.event.inputs.newversion}}"
          git push

      - name: Create tag
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/target/*.jar"
          bodyFile: changelog/${{github.event.inputs.version}}.md
          tag: ${{github.event.inputs.version}}

      - name: Publish to GitHub Packages
        run: mvn  --batch-mode deploy -Prelease
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}


      - name: Upgrade Version
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"

          mvn versions:set -DnewVersion=${{github.event.inputs.newversion}}
          git commit -am "new version release ${{github.event.inputs.newversion}}"
          git push